name: Build Executable with PyInstaller

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest  # Используем Windows для совместимости с вашей сборкой

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Укажите версию Python, которую используете

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller launcher.spec

    - name: Create release archive
      run: |
        cd dist
        Compress-Archive -Path launcher -DestinationPath OEEG_plot.zip

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: OEEG_plot-executable
        path: dist/OEEG_plot.zip
        retention-days: 30

    # Автоматически создаем release при создании тега
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/OEEG_plot.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}